name: Publish Package to npmjs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: |
          AUTH_URL="//registry.npmjs.org/:_authToken=$env.NPM_TOKEN"
          if [ -z "$AUTH_URL" ]; then
            echo "❌ AUTH_URL NÃO está definida"
            exit 1
          else
            echo "✅ AUTH_URL está definida corretamente"
          fi
      - run: npm ci
      - run: npm run test:github
      - run: npm run build:github
      - run: npm config set $AUTH_URL
      - run: npm run publish:github

